'use client';

import React, { useEffect, useState } from 'react';
import {
  X,
  Brain,
  RefreshCw,
  CheckCircle2,
  AlertTriangle,
  TrendingUp,
  Clock,
  Zap,
} from 'lucide-react';

import {
  FoodBatch,
  Decision,
  DecisionAlternative,
} from '@/app/types';

import AgentDecisionPipeline from './AgentDecisionPipeline';

interface DecisionIntelligencePanelProps {
  batch: FoodBatch;
  decision: Decision;
  onClose: () => void;
}

interface BackendRiskAssessment {
  product_name: string;
  risk_score: number;
  risk_level: string;
  confidence: number;
  factors: {
    expiry_risk: number;
    temperature_risk: number;
    demand_risk: number;
    logistics_risk: number;
  };
  recommended_action: string;
}

const getRiskColor = (riskLevel: string) => {
  switch (riskLevel.toLowerCase()) {
    case 'low':
      return 'text-emerald-400';
    case 'medium':
      return 'text-yellow-400';
    case 'high':
      return 'text-orange-400';
    case 'critical':
      return 'text-red-400';
    default:
      return 'text-slate-300';
  }
};

const getOperationalRiskColor = (riskLevel: string) => {
  switch (riskLevel) {
    case 'low':
      return 'text-emerald-400';
    case 'medium':
      return 'text-yellow-400';
    case 'high':
      return 'text-red-400';
    default:
      return 'text-slate-300';
  }
};

export default function DecisionIntelligencePanel({
  batch,
  decision,
  onClose,
}: DecisionIntelligencePanelProps) {
  const [backendAssessment, setBackendAssessment] =
    useState<BackendRiskAssessment | null>(null);

  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchRiskAssessment = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch('http://127.0.0.1:8000/predict-risk', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },

        body: JSON.stringify({
          product_name: batch.name,
          days_remaining: batch.daysRemaining,
          temperature_anomaly: 0,
          demand_multiplier: 1,
          logistics_delay_hours: 0,
          quantity_kg: batch.quantity,
        }),
      });

      if (!response.ok) {
        throw new Error('Unable to connect to the CHRONOS AI backend.');
      }

      const data: BackendRiskAssessment = await response.json();

      setBackendAssessment(data);
    } catch (err) {
      console.error('Backend risk assessment error:', err);

      setError(
        err instanceof Error
          ? err.message
          : 'Unable to retrieve the live AI risk assessment.'
      );
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchRiskAssessment();
  }, [batch.id]);

  const recommendedAlternative =
    decision.alternatives.find(
      (alternative) =>
        alternative.id === decision.selectedAlternativeId
    ) || decision.alternatives[0];

  return (
    <div className="fixed inset-0 z-50 bg-black/70 flex justify-end">
      <div className="h-full w-full max-w-6xl bg-slate-900 border-l border-slate-700 overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 z-10 bg-slate-900 border-b border-slate-700 px-8 py-6 flex items-start justify-between">
          <div>
            <h2 className="text-3xl font-bold text-white">
              Decision Intelligence
            </h2>

            <p className="text-slate-400 mt-1">
              Analyzing: {batch.name}
            </p>
          </div>

          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors p-2"
            aria-label="Close decision panel"
          >
            <X size={30} />
          </button>
        </div>

        <div className="p-8 space-y-8">

          {/* LIVE BACKEND AI ASSESSMENT */}
          <section className="border border-blue-600 rounded-xl bg-slate-800/70 p-8">
            <div className="flex items-start justify-between gap-6 mb-8">
              <div className="flex items-start gap-4">
                <div className="p-3 rounded-xl bg-blue-500/20">
                  <Brain className="text-blue-400" size={30} />
                </div>

                <div>
                  <div className="flex items-center gap-3 flex-wrap">
                    <h3 className="text-2xl font-bold text-white">
                      Live AI Risk Assessment
                    </h3>

                    <span className="px-3 py-1 rounded-full bg-emerald-900/70 text-emerald-300 text-sm font-medium">
                      FASTAPI CONNECTED
                    </span>
                  </div>

                  <p className="text-slate-400 mt-2">
                    Real-time risk assessment generated by the CHRONOS backend.
                  </p>
                </div>
              </div>

              <button
                onClick={fetchRiskAssessment}
                disabled={isLoading}
                className="p-3 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-200 transition-colors disabled:opacity-50"
                title="Refresh AI assessment"
              >
                <RefreshCw
                  size={22}
                  className={isLoading ? 'animate-spin' : ''}
                />
              </button>
            </div>

            {isLoading && (
              <div className="py-10 text-center text-slate-400">
                Connecting to CHRONOS AI backend...
              </div>
            )}

            {error && (
              <div className="border border-red-700 bg-red-950/40 rounded-lg p-5 text-red-300">
                <div className="flex items-center gap-3">
                  <AlertTriangle size={22} />
                  <span>{error}</span>
                </div>
              </div>
            )}

            {!isLoading && backendAssessment && (
              <>
                {/* Main AI Metrics */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-6">
                  <div className="bg-slate-700/70 rounded-xl p-5">
                    <p className="text-sm uppercase tracking-wider text-slate-400">
                      Live Risk Score
                    </p>

                    <p className="text-4xl font-bold text-emerald-400 mt-3">
                      {backendAssessment.risk_score}
                    </p>
                  </div>

                  <div className="bg-slate-700/70 rounded-xl p-5">
                    <p className="text-sm uppercase tracking-wider text-slate-400">
                      Risk Level
                    </p>

                    <p
                      className={`text-2xl font-bold mt-4 ${getRiskColor(
                        backendAssessment.risk_level
                      )}`}
                    >
                      {backendAssessment.risk_level}
                    </p>
                  </div>

                  <div className="bg-slate-700/70 rounded-xl p-5">
                    <p className="text-sm uppercase tracking-wider text-slate-400">
                      Model Confidence
                    </p>

                    {/* IMPORTANT: Backend already returns confidence as a percentage */}
                    <p className="text-3xl font-bold text-blue-400 mt-3">
                      {Number(backendAssessment.confidence).toFixed(2)}%
                    </p>
                  </div>
                </div>

                {/* Backend Recommendation */}
                <div className="border border-blue-600/70 bg-blue-950/30 rounded-xl p-5 mb-6">
                  <p className="text-sm uppercase tracking-wider font-semibold text-blue-300 mb-2">
                    Backend Recommendation
                  </p>

                  <p className="text-lg font-medium text-white">
                    {backendAssessment.recommended_action}
                  </p>
                </div>

                {/* Backend Risk Factors */}
                <div>
                  <p className="text-sm uppercase tracking-wider text-slate-400 mb-4">
                    Backend Risk Factors
                  </p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    <RiskFactorCard
                      label="Expiry"
                      value={backendAssessment.factors.expiry_risk}
                    />

                    <RiskFactorCard
                      label="Temperature"
                      value={backendAssessment.factors.temperature_risk}
                    />

                    <RiskFactorCard
                      label="Demand"
                      value={backendAssessment.factors.demand_risk}
                    />

                    <RiskFactorCard
                      label="Logistics"
                      value={backendAssessment.factors.logistics_risk}
                    />
                  </div>
                </div>
              </>
            )}
          </section>

          {/* AUTONOMOUS AGENT PIPELINE */}
          <section>
            <AgentDecisionPipeline
              decision={decision}
            />
          </section>

          {/* CHRONOS RECOMMENDATION */}
          <section className="rounded-xl border border-emerald-600/60 bg-emerald-950/50 p-8">
            <div className="flex items-start justify-between gap-6">
              <div className="flex gap-4">
                <CheckCircle2
                  className="text-emerald-400 mt-1"
                  size={32}
                />

                <div>
                  <h3 className="text-2xl font-bold text-white">
                    {recommendedAlternative?.name ||
                      decision.recommendedActionName}
                  </h3>

                  <p className="text-slate-300 mt-4 leading-relaxed">
                    {recommendedAlternative?.explanation ||
                      decision.recommendedActionExplanation}
                  </p>
                </div>
              </div>

              <div className="text-right">
                <p className="text-xs uppercase tracking-wider text-emerald-300">
                  Recommendation Score
                </p>

                <p className="text-4xl font-bold text-emerald-300 mt-2">
                  {decision.recommendedActionScore}
                </p>
              </div>
            </div>
          </section>

          {/* KEY RISK FACTORS */}
          <section className="rounded-xl border border-slate-700 bg-slate-800 p-8">
            <div className="flex items-center gap-3 mb-6">
              <AlertTriangle className="text-orange-400" size={28} />

              <h3 className="text-2xl font-bold text-white">
                Key Risk Factors
              </h3>
            </div>

            <div className="space-y-6">
              {decision.riskFactors.map((factor) => (
                <div
                  key={factor.name}
                  className="grid grid-cols-[1fr_auto] gap-6 items-center"
                >
                  <div>
                    <h4 className="font-semibold text-white">
                      {factor.name}
                    </h4>

                    <p className="text-slate-400 text-sm mt-1">
                      {factor.description}
                    </p>
                  </div>

                  <div className="flex items-center gap-4 min-w-56">
                    <div className="h-3 flex-1 bg-slate-700 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-emerald-400 rounded-full"
                        style={{
                          width: `${Math.min(factor.score, 100)}%`,
                        }}
                      />
                    </div>

                    <span className="w-8 text-right font-bold text-white">
                      {factor.score}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* ACTION ALTERNATIVES */}
          <section className="rounded-xl border border-slate-700 bg-slate-800 p-8">
            <div className="flex items-center gap-3 mb-6">
              <TrendingUp className="text-blue-400" size={28} />

              <h3 className="text-2xl font-bold text-white">
                Action Alternatives
              </h3>
            </div>

            <div className="space-y-4">
              {decision.alternatives.map(
                (alternative: DecisionAlternative) => {
                  const isRecommended =
                    alternative.id ===
                    recommendedAlternative?.id;

                  return (
                    <div
                      key={alternative.id}
                      className={`rounded-xl border p-5 transition-colors ${
                        isRecommended
                          ? 'border-blue-500 bg-blue-950/40'
                          : 'border-slate-600 bg-slate-800'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-6">
                        <div>
                          <h4 className="text-xl font-bold text-white">
                            {alternative.name}
                          </h4>

                          <p className="text-slate-400 mt-2">
                            {alternative.description}
                          </p>

                          <div className="flex gap-5 mt-4 text-sm">
                            <span className="text-slate-400">
                              Waste reduction:{' '}
                              <strong className="text-white">
                                {alternative.wasteReductionPercent}%
                              </strong>
                            </span>

                            <span className="text-slate-400">
                              Operational risk:{' '}
                              <strong
                                className={getOperationalRiskColor(
                                  alternative.operationalRiskLevel
                                )}
                              >
                                {alternative.operationalRiskLevel}
                              </strong>
                            </span>
                          </div>
                        </div>

                        <div className="text-right">
                          <p className="text-xs uppercase tracking-wider text-slate-400">
                            Score
                          </p>

                          <p className="text-3xl font-bold text-white mt-1">
                            {alternative.overallScore}
                          </p>
                        </div>
                      </div>
                    </div>
                  );
                }
              )}
            </div>
          </section>

          {/* DECISION STATUS */}
          <section className="rounded-xl border border-slate-700 bg-slate-800 p-6">
            <div className="flex flex-wrap gap-8">
              <div className="flex items-center gap-3">
                <Zap className="text-yellow-400" size={22} />

                <div>
                  <p className="text-xs text-slate-400 uppercase">
                    Execution Mode
                  </p>

                  <p className="text-white font-semibold capitalize">
                    {decision.executionMode.replace('-', ' ')}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-3">
                <Clock className="text-blue-400" size={22} />

                <div>
                  <p className="text-xs text-slate-400 uppercase">
                    Decision Status
                  </p>

                  <p className="text-white font-semibold capitalize">
                    {decision.status}
                  </p>
                </div>
              </div>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}

interface RiskFactorCardProps {
  label: string;
  value: number;
}

function RiskFactorCard({
  label,
  value,
}: RiskFactorCardProps) {
  return (
    <div className="bg-slate-700/70 rounded-xl p-4">
      <p className="text-sm text-slate-400">
        {label}
      </p>

      <p className="text-2xl font-bold text-white mt-2">
        {value}
      </p>
    </div>
  );
}